"""empty message

Revision ID: 81c3abd2b5f2
Revises: 
Create Date: 2019-05-10 20:27:18.984057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c3abd2b5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carSeries', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_carSeries'), 'brand', ['carSeries'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('preference', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chooseSeries', sa.String(), nullable=True),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chooseSeries'], ['brand.carSeries'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserId')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('choice')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_brand_carSeries'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
